title: SQL Sage Documentation
description: Developer documentation for SQL Sage
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true

plugins:
  - jekyll-remote-theme

aux_links:
  Repository:
    - "{{ site.github.repository_url }}"

footer_content: "SQL Sage documentation"

exclude:
  - specs
  - data
  - dist
  - models
  - node_modules
  - coverage
  - scripts
  - src
  - .sqlsage
  - package-lock.json
